Vagrant.configure(2) do |config|

  config.vm.box = "archlinux/archlinux"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo pacman -Syu libzip zlib webkit2gtk jdk8-openjdk base-devel git bash cmake vim unzip --needed --noconfirm
    curl -O https://download.clojure.org/install/linux-install-1.9.0.358.sh
    chmod +x linux-install-1.9.0.358.sh
    sudo ./linux-install-1.9.0.358.sh
  SHELL
end
